var cuid = require('cuid')

console.log(cuid())
console.log(cuid())
console.log(cuid())
console.log(cuid())
console.log(cuid())
console.log(cuid())
console.log(cuid())
console.log(cuid())
console.log(cuid())
console.log(cuid())
